import requests
from requests.auth import HTTPBasicAuth
from datetime import datetime
from config import Config


def get_auth():
    return HTTPBasicAuth(Config.SNOW_USERNAME, Config.SNOW_PASSWORD)


def get_headers():
    return {
        'Content-Type': 'application/json',
        'Accept':       'application/json'
    }


def create_incident(vm_name, action, user_name, user_email,
                    resource_group, status, message):
    """
    Creates a ServiceNow Incident for every VM action
    Returns the incident number e.g. INC0012345
    """

    action_descriptions = {
        'start':   'VM Start Operation',
        'stop':    'VM Stop/Deallocate Operation',
        'restart': 'VM Restart Operation'
    }

    # State: 1=New, 2=In Progress, 6=Resolved
    snow_state = '6' if status == 'success' else '1'

    payload = {
        'short_description': (
            f"VM Action: {action.upper()} - {vm_name}"
        ),
        'description': (
            f"VM Management Action Performed\n"
            f"{'─' * 40}\n"
            f"Action:         {action_descriptions.get(action, action)}\n"
            f"VM Name:        {vm_name}\n"
            f"Resource Group: {resource_group}\n"
            f"Performed By:   {user_name} ({user_email})\n"
            f"Result:         {status.upper()}\n"
            f"Message:        {message}\n"
            f"Timestamp:      {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
            f"Portal:         VM Self-Service Portal\n"
        ),
        'category':     'Cloud Operations',
        'subcategory':  'Virtual Machine',
        'caller_id':    'admin',
        'impact':       '3',
        'urgency':      '3',
        'state':        snow_state,

        # Mandatory fields when state is Resolved (6)
        'close_code':   'Solved (Permanently)',
        'close_notes':  (
            f"VM {action.upper()} action "
            f"{'completed successfully' if status == 'success' else 'failed'} "
            f"via VM Self-Service Portal by {user_name}"
        ),

        'comments': "Auto-generated by VM Self-Service Portal"
    }

    try:
        url = f"{Config.SNOW_INSTANCE_URL}/api/now/table/incident"

        response = requests.post(
            url,
            json=payload,
            auth=get_auth(),
            headers=get_headers(),
            timeout=10
        )

        if response.status_code == 201:
            incident_number = response.json()['result']['number']
            incident_sys_id = response.json()['result']['sys_id']
            return {
                'success':         True,
                'incident_number': incident_number,
                'incident_sys_id': incident_sys_id,
                'incident_url':    (
                    f"{Config.SNOW_INSTANCE_URL}"
                    f"/nav_to.do?uri=incident.do?sys_id={incident_sys_id}"
                )
            }
        else:
            return {
                'success': False,
                'error':   f"ServiceNow returned {response.status_code}: {response.text}"
            }

    except requests.exceptions.ConnectionError:
        return {
            'success': False,
            'error':   'Cannot connect to ServiceNow — check your PDI is awake'
        }
    except requests.exceptions.Timeout:
        return {
            'success': False,
            'error':   'ServiceNow request timed out'
        }
    except Exception as e:
        return {
            'success': False,
            'error':   str(e)
        }


def test_connection():
    try:
        url = (
            f"{Config.SNOW_INSTANCE_URL}"
            f"/api/now/table/incident?sysparm_limit=1"
        )
        response = requests.get(
            url,
            auth=get_auth(),
            headers=get_headers(),
            timeout=10
        )
        if response.status_code == 200:
            return {
                'success': True,
                'message': 'ServiceNow connection successful'
            }
        else:
            return {
                'success': False,
                'error':   f"Status {response.status_code}"
            }
    except Exception as e:
        return {'success': False, 'error': str(e)}
